### ISSUE TITLE
Error when "flux_upper_limits" is empty

### ISSUE THREAD

**Issue by Banafsheh89** [dankocevski/pyLCR#1]
Hi,
There are cases, for example obj="4FGL J0700.5-6610" and cadence monthly where there are no flux upper limit and thus the JSON file has empty list for that column. In such cases, the pyLCR code gives an error while the list doesn't have element 0 and 1. Very easy to fix in the code by adding a if condition.

**Comment by dankocevski** [comment]
Thank you of the fix!
