### ISSUE TITLE
Typo in plotLightCurve (candence)

### ISSUE THREAD

**Issue by andresgur** [dankocevski/pyLCR#8]
From plotLightCurve

`    # Quantify the cadence
    if 'daily' in cadence:
        duration = 259200
    elif 'weekly' in candence:
        duration = 604800
    elif 'monthly' in cadence:
        duration = 2592000`
        
 in weekly it should be "cadence" not candence

**Comment by carlosm-silva** [comment]
This issue should be fixed in pull requests #7 and #4, as both contain commit https://github.com/dankocevski/pyLCR/pull/7/commits/d889d03338c0e492fc2b8ab641148691bb7bee2b

**Comment by dankocevski** [comment]
Thank you!
