### ISSUE TITLE
Improper y-axis for Energy Plots

### ISSUE THREAD

**Issue by carlosm-silva** [dankocevski/pyLCR#9]
The `pyLCR.plotLightCurve` method displays the y-axis as `r'Photons cm$^{-2}$ s$^{-1}$'` regardless of the `lightCurve` argument's `flux_type` property.

If `lightCurve.flux_type` is `energy`, then it should display `r'erg cm$^{-2}$ s$^{-1}$'` instead.

**Comment by dankocevski** [comment]
Thank you for implementing this fix, Carlos!
